/**
 * Data loading utilities for the policy tracker.
 * Reads JSON files generated by the Python fetch scripts.
 */

import fs from 'node:fs';
import path from 'node:path';

const DATA_DIR = path.join(process.cwd(), 'data');

export interface PolicyItem {
  id: string;
  title: string;
  description: string;
  link: string;
  date: string;
  source_id: string;
  source_name: string;
  source_short: string;
  sectors: string[];
  sector_slugs: string[];
  type: string;
  level?: string;  // 'central' or 'state'
  state?: string;  // state name if level === 'state'
}

export interface Amendment {
  date: string;
  field: string;
  old_value: string;
  new_value: string;
  source_id: string;
}

export interface MetaData {
  last_updated: string;
  total_policies: number;
  total_sources: number;
  total_sectors: number;
  sector_counts: Record<string, number>;
  source_counts: Record<string, number>;
}

function readJson<T>(filename: string, fallback: T): T {
  const filepath = path.join(DATA_DIR, filename);
  try {
    const raw = fs.readFileSync(filepath, 'utf-8');
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

// Civil Liberties auto-tagging keywords
const CIVIL_LIBERTIES_KEYWORDS = /\b(uapa|sedition|rti|right to information|habeas corpus|custodial death|internet shutdown|press freedom|free speech|fundamental right|civil libert|human rights|nhrc|detention|undertrial|bail|remand|fir|arrest|censorship|surveillance|privacy|personal data protection|digital personal data|aadhaar|free expression|protest|assembly|dissent|section 144|nsa |national security act|psa |public safety act|afspa|armed forces special|defamation|contempt of court|encounter|extrajudicial|minority rights|religious freedom|caste atrocit|sc.st.*prevention|bonded labour|child labour|trafficking|forced disappearance|press council|media regulation)\b/i;

function tagCivilLiberties(policies: PolicyItem[]): PolicyItem[] {
  for (const p of policies) {
    if (p.sectors.includes('Civil Liberties')) continue;
    const text = `${p.title} ${p.description || ''}`;
    if (CIVIL_LIBERTIES_KEYWORDS.test(text)) {
      p.sectors = [...p.sectors, 'Civil Liberties'];
      p.sector_slugs = [...(p.sector_slugs || []), 'civil-liberties'];
    }
  }
  return policies;
}

export function getAllPolicies(): PolicyItem[] {
  const scraped = readJson<PolicyItem[]>('policies.json', getSamplePolicies());
  const historical = readJson<PolicyItem[]>('historical_policies.json', []);

  // Merge, deduplicate by id, sort by date descending
  const byId = new Map<string, PolicyItem>();
  for (const p of scraped) byId.set(p.id, p);
  for (const p of historical) {
    if (!byId.has(p.id)) byId.set(p.id, p);
  }
  const merged = Array.from(byId.values()).sort((a, b) => b.date.localeCompare(a.date));
  return tagCivilLiberties(merged);
}

export function getMeta(): MetaData {
  const policies = getAllPolicies();
  const sectorCounts: Record<string, number> = {};
  const sourceCounts: Record<string, number> = {};

  for (const p of policies) {
    for (const s of p.sectors) {
      sectorCounts[s] = (sectorCounts[s] || 0) + 1;
    }
    sourceCounts[p.source_short] = (sourceCounts[p.source_short] || 0) + 1;
  }

  const stored = readJson<Partial<MetaData>>('meta.json', {});

  // Read total configured sources from feeds.json (not just ones that returned data)
  let totalConfiguredSources = Object.keys(sourceCounts).length;
  try {
    const feedsPath = path.join(process.cwd(), 'feeds.json');
    const feedsRaw = fs.readFileSync(feedsPath, 'utf-8');
    const feeds = JSON.parse(feedsRaw);
    if (feeds?.sources) {
      totalConfiguredSources = Object.keys(feeds.sources).length;
    }
  } catch { /* fall back to source_counts */ }

  return {
    last_updated: stored.last_updated || new Date().toISOString(),
    total_policies: policies.length,
    total_sources: totalConfiguredSources,
    total_sectors: Object.keys(sectorCounts).length,
    sector_counts: sectorCounts,
    source_counts: sourceCounts,
  };
}

export function getPoliciesBySector(sectorSlug: string): PolicyItem[] {
  return getAllPolicies().filter(p => p.sector_slugs.includes(sectorSlug));
}

export function getPoliciesBySource(sourceShort: string): PolicyItem[] {
  return getAllPolicies().filter(p => p.source_short === sourceShort);
}

export function getSectorSlug(sector: string): string {
  return sector.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-');
}

export function getAllSectorSlugs(): string[] {
  const meta = getMeta();
  return Object.keys(meta.sector_counts).map(getSectorSlug);
}

export function getAllSourceShorts(): string[] {
  const meta = getMeta();
  return Object.keys(meta.source_counts);
}

export function getPolicyById(id: string): PolicyItem | undefined {
  return getAllPolicies().find(p => p.id === id);
}

export function getRelatedPolicies(policy: PolicyItem, limit = 5): PolicyItem[] {
  const all = getAllPolicies();
  return all
    .filter(p => p.id !== policy.id && p.sector_slugs.some(s => policy.sector_slugs.includes(s)))
    .slice(0, limit);
}

/** Returns { 'YYYY-MM-DD': count } for the heatmap */
export function getDailyActivity(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const p of getAllPolicies()) {
    counts[p.date] = (counts[p.date] || 0) + 1;
  }
  return counts;
}

/** Returns { 'YYYY-WW': count } for weekly trends */
export function getWeeklyTrends(): { week: string; count: number }[] {
  const weekly: Record<string, number> = {};
  for (const p of getAllPolicies()) {
    const d = new Date(p.date);
    const year = d.getFullYear();
    const jan1 = new Date(year, 0, 1);
    const weekNum = Math.ceil(((d.getTime() - jan1.getTime()) / 86400000 + jan1.getDay() + 1) / 7);
    const key = `${year}-W${String(weekNum).padStart(2, '0')}`;
    weekly[key] = (weekly[key] || 0) + 1;
  }
  return Object.entries(weekly)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([week, count]) => ({ week, count }));
}

/** Returns type distribution */
export function getTypeDistribution(): { type: string; count: number; pct: number }[] {
  const types: Record<string, number> = {};
  const all = getAllPolicies();
  for (const p of all) {
    types[p.type] = (types[p.type] || 0) + 1;
  }
  return Object.entries(types)
    .sort(([, a], [, b]) => b - a)
    .map(([type, count]) => ({ type, count, pct: Math.round((count / all.length) * 100) }));
}

/** Returns top N most active sectors */
export function getTopSectors(n = 6): { sector: string; slug: string; count: number }[] {
  const meta = getMeta();
  return Object.entries(meta.sector_counts)
    .sort(([, a], [, b]) => b - a)
    .slice(0, n)
    .map(([sector, count]) => ({ sector, slug: getSectorSlug(sector), count }));
}

/** Returns a structured insight for a given sector */
export interface SectorInsight {
  name: string;
  slug: string;
  total: number;
  recentCount: number; // last 30 days
  typeBreakdown: { type: string; count: number }[];
  topSources: { source: string; count: number }[];
  latestPolicy: PolicyItem | null;
  relatedSectors: string[]; // sectors that co-occur most
}

export function getSectorInsight(sectorName: string): SectorInsight {
  const slug = getSectorSlug(sectorName);
  const policies = getPoliciesBySector(slug);
  const now = Date.now();
  const DAY = 86400000;

  // Type breakdown
  const types: Record<string, number> = {};
  for (const p of policies) types[p.type] = (types[p.type] || 0) + 1;
  const typeBreakdown = Object.entries(types)
    .sort(([, a], [, b]) => b - a)
    .map(([type, count]) => ({ type, count }));

  // Top sources
  const sources: Record<string, number> = {};
  for (const p of policies) sources[p.source_short] = (sources[p.source_short] || 0) + 1;
  const topSources = Object.entries(sources)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 3)
    .map(([source, count]) => ({ source, count }));

  // Related sectors (co-occurrence)
  const coSectors: Record<string, number> = {};
  for (const p of policies) {
    for (const s of p.sectors) {
      if (s !== sectorName) coSectors[s] = (coSectors[s] || 0) + 1;
    }
  }
  const relatedSectors = Object.entries(coSectors)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 4)
    .map(([s]) => s);

  return {
    name: sectorName,
    slug,
    total: policies.length,
    recentCount: policies.filter(p => now - new Date(p.date).getTime() < 30 * DAY).length,
    typeBreakdown,
    topSources,
    latestPolicy: policies[0] || null,
    relatedSectors,
  };
}

/** Returns policy count by government era */
export function getEraDistribution(): { era: string; party: string; count: number; dateRange: string }[] {
  const eras = [
    { name: 'UPA I',   party: 'Congress-led UPA',  start: '2004-05-22', end: '2009-05-21' },
    { name: 'UPA II',  party: 'Congress-led UPA',  start: '2009-05-22', end: '2014-05-25' },
    { name: 'NDA I',   party: 'BJP-led NDA',       start: '2014-05-26', end: '2019-05-29' },
    { name: 'NDA II',  party: 'BJP-led NDA',       start: '2019-05-30', end: '2024-06-08' },
    { name: 'NDA III', party: 'BJP-led NDA',       start: '2024-06-09', end: '9999-12-31' },
  ];
  const all = getAllPolicies();
  return eras.map(era => ({
    era: era.name,
    party: era.party,
    count: all.filter(p => p.date >= era.start && p.date <= era.end).length,
    dateRange: `${era.start.slice(0,4)}–${era.end === '9999-12-31' ? 'Present' : era.end.slice(0,4)}`,
  }));
}

/** State government data */
export interface StateGovInfo {
  name: string;
  abbr: string;
  party: string;
  cm?: string;
  lg?: string;
  lean: number;
  label: string;
  since?: string;
  type: 'state' | 'ut';
}

export function getStateGovernments(): StateGovInfo[] {
  const data = readJson<any>('state_governments.json', { states: {}, union_territories: {} });
  const result: StateGovInfo[] = [];
  for (const [name, info] of Object.entries(data.states || {})) {
    const s = info as any;
    result.push({ name, abbr: s.abbr, party: s.party, cm: s.cm, lean: s.lean, label: s.label, since: s.since, type: 'state' });
  }
  for (const [name, info] of Object.entries(data.union_territories || {})) {
    const s = info as any;
    result.push({ name, abbr: s.abbr, party: s.party, cm: s.cm, lg: s.lg, lean: s.lean, label: s.label, type: 'ut' });
  }
  return result;
}

export function getStateSlug(name: string): string {
  return name.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-');
}

export function getPoliciesByState(stateName: string): PolicyItem[] {
  return getAllPolicies().filter(p => p.state === stateName);
}

export function getStatePolicySummary(): { name: string; slug: string; count: number; party: string; label: string; abbr: string; type: 'state' | 'ut' }[] {
  const govs = getStateGovernments();
  const policies = getAllPolicies();

  // Count policies by state
  const stateCounts: Record<string, number> = {};
  for (const p of policies) {
    if (p.state) {
      stateCounts[p.state] = (stateCounts[p.state] || 0) + 1;
    }
  }

  return govs.map(g => ({
    name: g.name,
    slug: getStateSlug(g.name),
    count: stateCounts[g.name] || 0,
    party: g.party,
    label: g.label,
    abbr: g.abbr,
    type: g.type,
  }));
}

/** Policy continuity chain data */
export interface ContinuityStep {
  name: string;
  era: string;
  year: number;
  party: string;
  status: 'active' | 'superseded';
  description: string;
}

export interface PolicyChain {
  id: string;
  theme: string;
  sector: string;
  timeline: ContinuityStep[];
  analysis: string;
}

export function getPolicyContinuityChains(): PolicyChain[] {
  const data = readJson<any>('policy_continuity.json', { chains: [] });
  return data.chains || [];
}

/** Budget allocation data */
export interface FiscalSummary {
  year: string;
  total_expenditure: number;
  revenue_expenditure: number;
  capital_expenditure: number;
  fiscal_deficit_pct_gdp: number;
  gdp_estimate: number;
  type: string;
}

export interface AllocationEntry {
  year: string;
  amount: number;
  type: string;
}

export interface MinistryAllocation {
  ministry: string;
  sector: string;
  allocations: AllocationEntry[];
}

export interface SchemeAllocation {
  scheme: string;
  ministry: string;
  sector: string;
  allocations: AllocationEntry[];
}

export interface BudgetData {
  fiscal_summary: FiscalSummary[];
  ministry_allocations: MinistryAllocation[];
  major_schemes: SchemeAllocation[];
}

export function getBudgetData(): BudgetData {
  const data = readJson<any>('budget_allocations.json', {
    fiscal_summary: [],
    ministry_allocations: [],
    major_schemes: [],
  });
  return {
    fiscal_summary: data.fiscal_summary || [],
    ministry_allocations: data.ministry_allocations || [],
    major_schemes: data.major_schemes || [],
  };
}

/** State-level curated policy data */
export interface StateFlagshipScheme {
  name: string;
  sector: string;
  year: number;
  allocation_crore: number;
  description: string;
  status: 'active' | 'discontinued' | 'proposed';
}

export interface StateKeyPolicy {
  title: string;
  date: string;
  sector: string;
}

export interface StateProfileData {
  gsdp_lakh_crore: number;
  gsdp_rank: number;
  population_crore: number;
  hdi: number;
  flagship_schemes: StateFlagshipScheme[];
  key_policies: StateKeyPolicy[];
}

export function getStateProfile(stateName: string): StateProfileData | null {
  const data = readJson<any>('state_policies.json', { states: {} });
  return data.states?.[stateName] || null;
}

export function getAllStateProfiles(): Record<string, StateProfileData> {
  const data = readJson<any>('state_policies.json', { states: {} });
  return data.states || {};
}

/** Policy impact annotations */
export interface PolicyImpact {
  match_keywords: string[];
  impact_score: number;
  beneficiaries: string;
  budget_crore: number;
  implementation: 'announced' | 'early' | 'partial' | 'operational';
  implementation_pct: number;
  outcomes: string[];
  challenges: string[];
  sdg_goals: number[];
  states_covered: string;
}

export function getImpactForPolicy(title: string): PolicyImpact | null {
  const data = readJson<any>('policy_impacts.json', { impacts: {} });
  const impacts = data.impacts || {};
  const titleLower = title.toLowerCase();
  for (const [, impact] of Object.entries(impacts)) {
    const imp = impact as PolicyImpact;
    if (imp.match_keywords?.some((kw: string) => titleLower.includes(kw.toLowerCase()))) {
      return imp;
    }
  }
  return null;
}

export function getAllImpacts(): Record<string, PolicyImpact> {
  const data = readJson<any>('policy_impacts.json', { impacts: {} });
  return data.impacts || {};
}

/** Parliament session data */
export interface ParliamentSession {
  name: string;
  type: string;
  start: string;
  end: string;
  days_sat: number;
  days_scheduled: number;
  bills_introduced: number;
  bills_passed: number;
  key_events: string[];
  productivity_pct: number;
}

export interface PendingBill {
  name: string;
  introduced: string;
  status: string;
  sector: string;
}

export interface HistoricalProductivity {
  lok_sabha: number;
  term: string;
  bills_passed: number;
  avg_productivity: number;
}

export interface ParliamentData {
  lok_sabha: { current: number; term_start: string; speaker: string };
  sessions: ParliamentSession[];
  bills_tracker: { total_pending: number; referred_to_committee: number; passed_lok_sabha_only: number; key_pending_bills: PendingBill[] };
  historical_productivity: HistoricalProductivity[];
}

export function getParliamentData(): ParliamentData {
  return readJson<ParliamentData>('parliament_sessions.json', {
    lok_sabha: { current: 18, term_start: '', speaker: '' },
    sessions: [],
    bills_tracker: { total_pending: 0, referred_to_committee: 0, passed_lok_sabha_only: 0, key_pending_bills: [] },
    historical_productivity: [],
  });
}

/** Committee report data from sansad.in (via ParliamentWatch integration) */
export interface CommitteeReport {
  committee_key: string;
  committee_name: string;
  sector: string;
  report_number: number;
  title: string;
  presented_in_ls: string | null;
  laid_in_rs: string | null;
  presented_to_speaker: string | null;
  pdf_url: string | null;
  pdf_url_hindi: string | null;
  lok_sabha: number;
  house: string;
}

export interface CommitteeSummary {
  key: string;
  name: string;
  sector: string;
  report_count: number;
}

export interface CommitteeReportsData {
  metadata: {
    last_updated: string;
    total_reports: number;
    total_committees: number;
    lok_sabha: number;
    source: string;
    attribution: string;
  };
  committee_summary: CommitteeSummary[];
  committees: Record<string, CommitteeReport[]>;
}

export function getCommitteeReports(): CommitteeReportsData {
  return readJson<CommitteeReportsData>('committee_reports.json', {
    metadata: { last_updated: '', total_reports: 0, total_committees: 0, lok_sabha: 18, source: '', attribution: '' },
    committee_summary: [],
    committees: {},
  });
}

export function getRecentCommitteeReports(limit = 20): CommitteeReport[] {
  const data = getCommitteeReports();
  const all: CommitteeReport[] = [];
  for (const reports of Object.values(data.committees)) {
    all.push(...reports);
  }
  // Sort by presentation date (most recent first)
  return all
    .filter(r => r.presented_in_ls || r.laid_in_rs)
    .sort((a, b) => {
      const dateA = a.presented_in_ls || a.laid_in_rs || '';
      const dateB = b.presented_in_ls || b.laid_in_rs || '';
      return dateB.localeCompare(dateA);
    })
    .slice(0, limit);
}

export function searchCommitteeReports(query: string): CommitteeReport[] {
  const data = getCommitteeReports();
  const q = query.toLowerCase();
  const results: CommitteeReport[] = [];
  for (const reports of Object.values(data.committees)) {
    for (const r of reports) {
      if (r.title.toLowerCase().includes(q) || r.committee_name.toLowerCase().includes(q)) {
        results.push(r);
      }
    }
  }
  return results;
}

/** Returns sectors x types matrix for landscape view */
export function getSectorTypeMatrix(): {
  sectors: string[];
  types: string[];
  matrix: Record<string, Record<string, number>>;
} {
  const all = getAllPolicies();
  const sectorSet = new Set<string>();
  const typeSet = new Set<string>();
  const matrix: Record<string, Record<string, number>> = {};

  for (const p of all) {
    typeSet.add(p.type);
    for (const s of p.sectors) {
      sectorSet.add(s);
      if (!matrix[s]) matrix[s] = {};
      matrix[s][p.type] = (matrix[s][p.type] || 0) + 1;
    }
  }

  const meta = getMeta();
  const sectors = Object.entries(meta.sector_counts)
    .sort(([, a], [, b]) => b - a)
    .map(([s]) => s);

  const types = ['legislation', 'notification', 'scheme', 'budget', 'research', 'announcement', 'policy']
    .filter(t => typeSet.has(t));

  return { sectors, types, matrix };
}

/**
 * Sample/seed data so the site builds even before first fetch
 */
function getSamplePolicies(): PolicyItem[] {
  return [
    {
      id: "sample001",
      title: "Union Budget 2026-27: Key Highlights for Development Sectors",
      description: "The Finance Minister presented the Union Budget with significant allocations for education, health, rural development and digital infrastructure.",
      link: "https://www.indiabudget.gov.in/",
      date: "2026-02-01",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Finance & Economy", "Education", "Health"],
      sector_slugs: ["finance-economy", "education", "health"],
      type: "budget"
    },
    {
      id: "sample002",
      title: "National Education Policy Implementation: Progress Report 2026",
      description: "NITI Aayog releases comprehensive assessment of NEP 2020 implementation covering curriculum reforms, teacher training, and higher education restructuring.",
      link: "https://www.niti.gov.in/",
      date: "2026-01-15",
      source_id: "niti_aayog",
      source_name: "NITI Aayog",
      source_short: "NITI",
      sectors: ["Education", "Governance & Reform"],
      sector_slugs: ["education", "governance-reform"],
      type: "research"
    },
    {
      id: "sample003",
      title: "Digital Personal Data Protection Rules 2026 Notified",
      description: "The Ministry of Electronics and IT notifies the final rules under the Digital Personal Data Protection Act, 2023 covering consent, data fiduciary obligations, and cross-border data flows.",
      link: "https://www.meity.gov.in/",
      date: "2026-01-20",
      source_id: "meity",
      source_name: "Ministry of Electronics and IT",
      source_short: "MeitY",
      sectors: ["Digital & Technology", "Governance & Reform"],
      sector_slugs: ["digital-technology", "governance-reform"],
      type: "notification"
    },
    {
      id: "sample004",
      title: "PM-KISAN: 18th Instalment Released Benefiting 9 Crore Farmers",
      description: "The 18th instalment under the Pradhan Mantri Kisan Samman Nidhi has been released, directly transferring funds to eligible farmer families across the country.",
      link: "https://www.pib.gov.in/",
      date: "2026-02-15",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Agriculture", "Social Protection"],
      sector_slugs: ["agriculture", "social-protection"],
      type: "scheme"
    },
    {
      id: "sample005",
      title: "Jal Jeevan Mission: 90% Rural Households Now Have Tap Water Connections",
      description: "The Jal Jeevan Mission crosses a major milestone with 90% of rural households now having functional household tap water connections.",
      link: "https://jaljeevanmission.gov.in/",
      date: "2026-02-20",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Water & Sanitation", "Rural Development"],
      sector_slugs: ["water-sanitation", "rural-development"],
      type: "announcement"
    },
    {
      id: "sample006",
      title: "India's Updated Nationally Determined Contribution Under Paris Agreement",
      description: "India submits its updated NDC to the UNFCCC, enhancing climate targets including 50% non-fossil fuel energy capacity by 2030 and net-zero by 2070.",
      link: "https://moef.gov.in/",
      date: "2026-01-25",
      source_id: "moefcc",
      source_name: "Ministry of Environment",
      source_short: "MoEFCC",
      sectors: ["Climate & Environment", "Energy"],
      sector_slugs: ["climate-environment", "energy"],
      type: "policy"
    },
    {
      id: "sample007",
      title: "RBI Monetary Policy: Repo Rate Cut to Support Growth",
      description: "The Reserve Bank of India's Monetary Policy Committee announces a 25 basis point reduction in the repo rate, citing easing inflation and the need to support economic growth.",
      link: "https://rbi.org.in/",
      date: "2026-02-07",
      source_id: "rbi",
      source_name: "Reserve Bank of India",
      source_short: "RBI",
      sectors: ["Finance & Economy"],
      sector_slugs: ["finance-economy"],
      type: "announcement"
    },
    {
      id: "sample008",
      title: "Labour Codes Implementation: Final Notification for Code on Social Security",
      description: "The Ministry of Labour and Employment issues the final notification for implementing the Code on Social Security 2020, covering gig workers and platform workers for the first time.",
      link: "https://labour.gov.in/",
      date: "2026-01-10",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Labour & Employment", "Social Protection", "Digital & Technology"],
      sector_slugs: ["labour-employment", "social-protection", "digital-technology"],
      type: "legislation"
    },
    {
      id: "sample009",
      title: "Women's Reservation Act: Delimitation Commission Progress Update",
      description: "PRS Legislative Research analysis of the implementation timeline for the Women's Reservation Act following the Census and delimitation exercise.",
      link: "https://prsindia.org/",
      date: "2026-02-10",
      source_id: "prs_legislative",
      source_name: "PRS Legislative Research",
      source_short: "PRS",
      sectors: ["Gender & Women", "Governance & Reform"],
      sector_slugs: ["gender-women", "governance-reform"],
      type: "research"
    },
    {
      id: "sample010",
      title: "India Semiconductor Mission: Three New Fab Units Approved",
      description: "The Cabinet approves establishment of three new semiconductor fabrication units under the India Semiconductor Mission with a combined investment of Rs 1.5 lakh crore.",
      link: "https://www.meity.gov.in/",
      date: "2026-02-25",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Digital & Technology", "Science & Innovation", "Trade & Commerce"],
      sector_slugs: ["digital-technology", "science-innovation", "trade-commerce"],
      type: "announcement"
    }
  ];
}

/* ── Source Type Classification ─────────────────────────────── */

const SOURCE_TYPE_MAP: Record<string, string> = {
  // ── Government: ministries, departments, PIB, scheme portals, state govts ──
  'PIB': 'government', 'PIB MH': 'government', 'PIB TN': 'government', 'PIB KA': 'government',
  'PIB WB': 'government', 'PIB UP': 'government', 'PIB GJ': 'government', 'PIB KL': 'government',
  'PIB MP': 'government', 'PIB RJ': 'government', 'PIB TS': 'government', 'PIB PB': 'government',
  'PIB NE': 'government', 'PIB BR': 'government',
  'NITI': 'government', 'NITI SDG': 'government', 'NITI Energy': 'government',
  'data.gov.in': 'government',
  'MoHFW': 'government', 'MoE': 'government', 'MoRD': 'government', 'MoHUA': 'government',
  'MoLE': 'government', 'Jal Shakti': 'government', 'MNRE': 'government', 'MCA': 'government',
  'MoTA': 'government', 'MWCD': 'government', 'MSJE': 'government', 'MEA': 'government',
  'DoJ': 'government', 'MoSPI': 'government', 'MoAgri': 'government', 'DoT': 'government',
  'Railways': 'government', 'DST': 'government', 'MoF Budget': 'government', 'MeitY': 'government',
  'MoEFCC': 'government', 'DGE': 'government', 'DPIIT': 'government', 'StartupIndia': 'government',
  'ECI': 'government', 'Historical': 'government',
  'MoCA-Av': 'government', 'MoCoal': 'government', 'MoCommerce': 'government', 'MoCA': 'government',
  'MoCoop': 'government', 'MoCulture': 'government', 'MoES': 'government', 'MoI&B': 'government',
  'MoMines': 'government', 'MoMSME': 'government', 'MoPR': 'government', 'MoPNG': 'government',
  'MoPower': 'government', 'MoRTH': 'government', 'MoShip': 'government', 'MoSteel': 'government',
  'MoTextile': 'government', 'MoYAS': 'government', 'MoAYUSH': 'government', 'MoFPI': 'government',
  'DoF': 'government', 'DEA': 'government', 'DFS': 'government', 'DoPT': 'government',
  'DoNER': 'government', 'DIPAM': 'government', 'DAE': 'government',
  'DRDO': 'government', 'ISRO': 'government', 'CSIR': 'government', 'NIC': 'government',
  'CAG': 'government', 'NHA': 'government', 'NFHS': 'government',
  'CBSE': 'government', 'NCERT': 'government', 'NCTE': 'government', 'NAAC': 'government',
  'ICMR': 'government', 'ICAR': 'government', 'ICSSR': 'government',
  'CBHI': 'government', 'NABH': 'government', 'NHM': 'government',
  'CERT-In': 'government', 'CIC': 'government',
  'NHRC': 'government', 'NCW': 'government', 'NCPCR': 'government', 'NCSC': 'government', 'NCST': 'government',
  'DBT': 'government', 'ABDM': 'government', 'DigiLocker': 'government', 'DigitalIndia': 'government',
  'GeM': 'government', 'MakeInIndia': 'government', 'SkillIndia': 'government',
  'PMAY': 'government', 'JJM': 'government', 'SBM': 'government', 'MGNREGA': 'government',
  'PMJAY': 'government', 'PM-KISAN': 'government', 'PMJDY': 'government', 'PMFBY': 'government',
  'POSHAN': 'government', 'AMRUT': 'government', 'SCM': 'government', 'MUDRA': 'government',
  'ONORC': 'government', 'StandUp': 'government', 'UJALA': 'government',
  'SamagraS': 'government', 'NSP': 'government', 'SHC': 'government',
  'eShram': 'government', 'UIDAI': 'government',
  'Lok Sabha': 'government', 'Rajya Sabha': 'government',
  // State governments
  'MH Govt': 'government', 'KA Govt': 'government', 'TN Govt': 'government',
  'KL Govt': 'government', 'Delhi Govt': 'government',
  'AP Govt': 'government', 'AR Govt': 'government', 'AS Govt': 'government',
  'BR Govt': 'government', 'CG Govt': 'government', 'GA Govt': 'government',
  'GJ Govt': 'government', 'HR Govt': 'government', 'HP Govt': 'government',
  'JH Govt': 'government', 'JK Govt': 'government', 'LA Govt': 'government',
  'MN Govt': 'government', 'ML Govt': 'government', 'MZ Govt': 'government',
  'NL Govt': 'government', 'OD Govt': 'government', 'PB Govt': 'government',
  'RJ Govt': 'government', 'SK Govt': 'government', 'TR Govt': 'government',
  'TS Govt': 'government', 'UP Govt': 'government', 'UK Govt': 'government',
  'MP Govt': 'government', 'WB Gaz': 'government',

  // ── Legal: courts, tribunals, law commission, bar council, legal media ──
  'India Code': 'legal', 'eGazette': 'legal', 'SCI': 'legal', 'Law Comm': 'legal',
  'LiveLaw': 'legal', 'Bar&Bench': 'legal', 'SCO': 'legal', 'NLSIU': 'legal',
  'Art14': 'legal', 'Vidhi': 'legal',
  'NCLAT': 'legal', 'NCLT': 'legal', 'ITAT': 'legal', 'TDSAT': 'legal', 'NGT': 'legal',
  'Lokpal': 'legal', 'CVC': 'legal', 'BCI': 'legal',

  // ── Regulator: independent regulatory bodies ──
  'RBI': 'regulator', 'SEBI': 'regulator', 'TRAI': 'regulator', 'IRDAI': 'regulator',
  'CCI': 'regulator', 'CERC': 'regulator', 'CPCB': 'regulator', 'FSSAI': 'regulator',
  'DGFT': 'regulator', 'CBIC': 'regulator', 'CBDT': 'regulator', 'IBBI': 'regulator',
  'NABARD': 'regulator', 'SIDBI': 'regulator', 'NHB': 'regulator',
  'UGC': 'regulator', 'AICTE': 'regulator', 'NMC': 'regulator',
  'DGCA': 'regulator', 'EPFO': 'regulator', 'ESIC': 'regulator',
  'NPCI': 'regulator', 'PFRDA': 'regulator', 'RERA': 'regulator',

  // ── Think tank: research orgs, universities, foundations, industry bodies ──
  'PRS Bills': 'think_tank', 'PRS': 'think_tank', 'ORF': 'think_tank', 'ORF Health': 'think_tank',
  'CPR': 'think_tank', 'ICRIER': 'think_tank', 'Brookings': 'think_tank', 'Carnegie': 'think_tank',
  'CSDS': 'think_tank', 'EPW': 'think_tank', 'CEEW': 'think_tank', 'TERI': 'think_tank',
  'CPPR': 'think_tank', 'CUTS': 'think_tank', 'IIMB': 'think_tank',
  'Takshashila': 'think_tank', 'CSE': 'think_tank', 'CBGA': 'think_tank',
  'IWWAGE': 'think_tank', 'J-PAL': 'think_tank', 'NCAER': 'think_tank',
  'IDFC': 'think_tank', 'NIPFP': 'think_tank', 'IndiaSpend': 'think_tank',
  'NASSCOM': 'think_tank', 'FICCI': 'think_tank', 'CII': 'think_tank',
  'APU': 'think_tank', 'RIS': 'think_tank', 'IIHS': 'think_tank',
  'IGIDR': 'think_tank', 'SPRF': 'think_tank', 'IIPS': 'think_tank',
  'GatewayH': 'think_tank', 'ChathamH': 'think_tank', 'CSIS': 'think_tank',
  'IndiaFound': 'think_tank', 'MP-IDSA': 'think_tank',
  'AI-CPRG': 'think_tank', 'Janaagraha': 'think_tank', 'Praja': 'think_tank',
  'Oxfam': 'think_tank', 'WiproF': 'think_tank',
  'SAV': 'think_tank', 'Drishti': 'think_tank', 'InsightsIAS': 'think_tank',

  // ── Media: news outlets, magazines, wire agencies ──
  'The Hindu': 'media', 'The Hindu Biz': 'media', 'IE': 'media', 'IE Biz': 'media',
  'ET': 'media', 'ET Infra': 'media', 'ET Energy': 'media', 'ET Govt': 'media', 'ET Health': 'media',
  'NDTV': 'media', 'The Wire': 'media',
  'Scroll': 'media', 'DH': 'media', 'HT': 'media', 'BS': 'media', 'BL': 'media',
  'Firstpost': 'media', 'News18': 'media', 'ThePrint': 'media', 'Quint': 'media',
  'DTE': 'media', 'Mint Op': 'media', 'Livemint': 'media',
  'Reuters': 'media', 'BBC': 'media', 'AlJazeera': 'media',
  'Tribune': 'media', 'Outlook': 'media', 'Caravan': 'media',
  'PTI': 'media', 'ANI': 'media',
  'MC': 'media', 'FE': 'media', 'DC': 'media',
  'AsianAge': 'media', 'Frontline': 'media', 'Swarajya': 'media',
  'Republic': 'media', 'Zee': 'media', 'NL': 'media',
  'IndiaToday': 'media', 'Telegraph': 'media',
  'Print Dip': 'media',

  // ── International: UN agencies, multilateral bodies ──
  'World Bank': 'international', 'UNDP': 'international', 'IMF': 'international',
  'ADB': 'international', 'UNICEF': 'international', 'WHO': 'international',
  'ILO': 'international', 'FAO': 'international',
  'OECD': 'international', 'WTO': 'international', 'IFC': 'international',
  'UNEP': 'international', 'UNDESA': 'international', 'UNFPA': 'international',
  'UNHCR': 'international',
};

export function getSourceType(sourceShort: string): string {
  return SOURCE_TYPE_MAP[sourceShort] || 'government';
}

export function getSourceTypeCounts(): Record<string, number> {
  const policies = getAllPolicies();
  const counts: Record<string, number> = { government: 0, legal: 0, think_tank: 0, international: 0, media: 0, regulator: 0 };
  for (const p of policies) {
    const t = getSourceType(p.source_short);
    counts[t] = (counts[t] || 0) + 1;
  }
  return counts;
}

/* ── Priority Scoring ──────────────────────────────────────── */

export function getPriority(policy: PolicyItem): 'critical' | 'high' | 'medium' | 'normal' {
  const t = policy.title.toLowerCase();
  const d = policy.description?.toLowerCase() || '';
  const combined = t + ' ' + d;

  // Critical: constitutional amendments, major acts, budget
  if (/constitutional amendment|finance bill|union budget|national security|emergency/i.test(combined)) return 'critical';
  if (policy.type === 'legislation' && /\bact\b|\bbill\b/i.test(t)) return 'critical';

  // High: major schemes, notifications with large scope
  if (/crore|lakh crore|billion|nationwide|all states|pan-india/i.test(combined)) return 'high';
  if (policy.type === 'scheme' && policy.sectors.length >= 2) return 'high';
  if (policy.type === 'notification' && /gazette|notification/i.test(t)) return 'high';

  // Medium: research, policy frameworks
  if (policy.type === 'research' || policy.type === 'policy') return 'medium';
  if (policy.sectors.length >= 3) return 'medium';

  return 'normal';
}

/* ── Trending Topics / Velocity ────────────────────────────── */

export interface TrendingTopic {
  sector: string;
  slug: string;
  count7d: number;
  count30d: number;
  velocity: number; // ratio of 7d to 30d normalized
}

export function getTrendingTopics(limit = 8): TrendingTopic[] {
  const policies = getAllPolicies();
  const now = new Date();
  const d7 = new Date(now.getTime() - 7 * 86400000);
  const d30 = new Date(now.getTime() - 30 * 86400000);

  const sectorMap: Record<string, { count7d: number; count30d: number; slug: string }> = {};

  for (const p of policies) {
    const pd = new Date(p.date);
    for (let i = 0; i < p.sectors.length; i++) {
      const sector = p.sectors[i];
      const slug = p.sector_slugs[i] || sector.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-');
      if (!sectorMap[sector]) sectorMap[sector] = { count7d: 0, count30d: 0, slug };
      if (pd >= d30) sectorMap[sector].count30d++;
      if (pd >= d7) sectorMap[sector].count7d++;
    }
  }

  return Object.entries(sectorMap)
    .map(([sector, data]) => ({
      sector,
      slug: data.slug,
      count7d: data.count7d,
      count30d: data.count30d,
      velocity: data.count30d > 0 ? (data.count7d / (data.count30d / 4.3)) : 0, // normalize to weekly
    }))
    .filter(t => t.count7d > 0)
    .sort((a, b) => b.velocity - a.velocity || b.count7d - a.count7d)
    .slice(0, limit);
}

/* ── Story Clustering ──────────────────────────────────────── */

export interface PolicyCluster {
  title: string;
  slug: string;
  policies: PolicyItem[];
  sectors: string[];
  latestDate: string;
}

function normalizeTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/\b(the|a|an|of|for|and|in|on|to|with|by|from)\b/g, '')
    .replace(/[^a-z0-9 ]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function titleSimilarity(a: string, b: string): number {
  const wordsA = new Set(normalizeTitle(a).split(' ').filter(w => w.length > 3));
  const wordsB = new Set(normalizeTitle(b).split(' ').filter(w => w.length > 3));
  if (wordsA.size === 0 || wordsB.size === 0) return 0;
  let overlap = 0;
  for (const w of wordsA) if (wordsB.has(w)) overlap++;
  return overlap / Math.min(wordsA.size, wordsB.size);
}

export function getStoryClusters(limit = 6): PolicyCluster[] {
  const policies = getAllPolicies().slice(0, 200); // recent policies
  const clusters: PolicyCluster[] = [];
  const used = new Set<string>();

  for (let i = 0; i < policies.length; i++) {
    if (used.has(policies[i].id)) continue;

    const group = [policies[i]];
    for (let j = i + 1; j < policies.length; j++) {
      if (used.has(policies[j].id)) continue;
      // Same sector overlap + title similarity
      const sectorOverlap = policies[i].sectors.some(s => policies[j].sectors.includes(s));
      const sim = titleSimilarity(policies[i].title, policies[j].title);
      if (sectorOverlap && sim >= 0.4) {
        group.push(policies[j]);
      }
    }

    if (group.length >= 2) {
      for (const p of group) used.add(p.id);
      const allSectors = [...new Set(group.flatMap(p => p.sectors))];
      clusters.push({
        title: group[0].title.length > 80 ? group[0].title.slice(0, 77) + '...' : group[0].title,
        slug: group[0].id,
        policies: group.slice(0, 5),
        sectors: allSectors,
        latestDate: group[0].date,
      });
    }
  }

  return clusters.sort((a, b) => b.policies.length - a.policies.length).slice(0, limit);
}

/* ── Daily Digest ──────────────────────────────────────────── */

export interface DailyDigest {
  date: string;
  totalPolicies: number;
  bySector: { sector: string; count: number }[];
  byType: { type: string; count: number }[];
  topPolicies: PolicyItem[];
  criticalCount: number;
}

export function getDailyDigest(dateStr?: string): DailyDigest {
  const policies = getAllPolicies();
  const targetDate = dateStr || policies[0]?.date || new Date().toISOString().slice(0, 10);

  const dayPolicies = policies.filter(p => p.date === targetDate);

  const sectorCounts: Record<string, number> = {};
  const typeCounts: Record<string, number> = {};
  let criticalCount = 0;

  for (const p of dayPolicies) {
    for (const s of p.sectors) sectorCounts[s] = (sectorCounts[s] || 0) + 1;
    typeCounts[p.type] = (typeCounts[p.type] || 0) + 1;
    if (getPriority(p) === 'critical') criticalCount++;
  }

  return {
    date: targetDate,
    totalPolicies: dayPolicies.length,
    bySector: Object.entries(sectorCounts)
      .map(([sector, count]) => ({ sector, count }))
      .sort((a, b) => b.count - a.count),
    byType: Object.entries(typeCounts)
      .map(([type, count]) => ({ type, count }))
      .sort((a, b) => b.count - a.count),
    topPolicies: dayPolicies.slice(0, 10),
    criticalCount,
  };
}

/* ── Recent Dates with Activity ────────────────────────────── */

export function getRecentActiveDates(limit = 7): string[] {
  const policies = getAllPolicies();
  const dates = [...new Set(policies.map(p => p.date))];
  return dates.sort((a, b) => b.localeCompare(a)).slice(0, limit);
}

/* ── Amendment Tracking ──────────────────────────────────── */

export function getAmendments(): Record<string, Amendment[]> {
  return readJson<Record<string, Amendment[]>>('amendments.json', {});
}

export function getAmendmentsForPolicy(id: string): Amendment[] {
  const all = getAmendments();
  return all[id] || [];
}

export function getRecentAmendments(limit = 20): { policy: PolicyItem; amendments: Amendment[] }[] {
  const all = getAmendments();
  const policies = getAllPolicies();
  const policyMap = new Map<string, PolicyItem>();
  for (const p of policies) policyMap.set(p.id, p);

  // Build entries with the most recent amendment date for sorting
  const entries: { policy: PolicyItem; amendments: Amendment[]; latestDate: string }[] = [];

  for (const [id, amendments] of Object.entries(all)) {
    if (amendments.length === 0) continue;
    const policy = policyMap.get(id);
    if (!policy) continue;
    const latestDate = amendments.reduce((max, a) => a.date > max ? a.date : max, '');
    entries.push({ policy, amendments, latestDate });
  }

  return entries
    .sort((a, b) => b.latestDate.localeCompare(a.latestDate))
    .slice(0, limit)
    .map(({ policy, amendments }) => ({ policy, amendments }));
}
